image: maven:latest
stages:
- validate
- build
- merge-request-only-build
- test
- merge-train-only-test
- package
validate:
  stage: validate
  # tags:
  # - comp3013j
  script:
  - echo "==============================  Validate =============================="
  - mvn clean
  - mvn validate
build:
  stage: build
  # tags:
  # - comp3013j
  script:
  - echo "==============================  Build =============================="
  - mvn clean
  - mvn compile
UnitTest:
  stage: test
  # tags:
  # - comp3013j
  script:
  - echo "============================== TEST =============================="
  - mvn clean
  - mvn test -X
  - cat target/site/jacoco/index.html



# package
package:
  stage: package
  only:
    - master
  # tags:
  # - comp3013j
  script:
  - echo "============================== package  =============================="
  - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
    - "/builds/comp3013-2021/group4/comp3013j_assignment/target/COMP3013J-1.0-SNAPSHOT-shaded.jar"
    - "/builds/comp3013-2021/group4/comp3013j_assignment/target/COMP3013J-1.0-SNAPSHOT.jar"
    expire_in: 2 week
merge-request-only-build:
  stage: merge-request-only-build
  # tags:
  # - comp3013j
  script:
  - echo "============================== Merge Build =============================="
  - mvn clean
  - mvn compile
  only:
    refs:
    - merge_requests
    variables:
    - $CI_MERGE_REQUEST_EVENT_TYPE == "merged_result"
merge-train-only-test:
  stage: merge-train-only-test
  # tags:
  # - comp3013j
  script:
  - echo "============================== Merge TEST =============================="
  - mvn clean
  - mvn test -X
  only:
    refs:
    - merge_requests
    variables:
    - $CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"


license_scanning:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
secret_detection_default_branch:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
gemnasium-maven-dependency_scanning:
    rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

